# Generated by Django 5.2 on 2025-04-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_board', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
